### ISSUE TITLE
(gdk): Can't publish component with s3 artifact URIs

### ISSUE THREAD

**Issue by BillMcGuinness** [aws-greengrass/aws-greengrass-gdk-cli#104]
**Describe the bug**
Can't publish component that has s3 artifact URIs in the recipe that don't exist locally.

**To Reproduce**
Create manifest with s3 URIs other than the source code zip, that don't exist locally.  run `gdk component publish`

**Expected behavior**
Component is published using s3 URIs in its artifacts.  URI with `s3://BUCKET_NAME/COMPNENT_NAME/COMPONENT_VERSION` gets values replaced, other URIs are left alone

**Actual behavior**
Error was raised 
`Could not find the artifact file specified in the recipe '<my s3 file>' inside the build folder '<my build folder>'`

**Environment**
 - OS: Darwin 19.6.0
 - JDK version: n/a
 - Nucleus version: n/a
 - GDK version: 1.1.0

**Additional context**
Documentation says "If you use GDK CLI v1.1.0 or later, the component recipe can specify artifacts that exist in an s3 bucket but not in the local component build folder".  That's basically what I'm trying to do

Bug prevents me from publishing my component using GDK CLI

**Comment by BillMcGuinness** [comment]
A work-around that allowed me to publish was to `log.info` instead of `raise Exception` [here](https://github.com/aws-greengrass/aws-greengrass-gdk-cli/blob/main/gdk/commands/component/PublishCommand.py#L342).  just skip renaming URI if file doesn't exist locally.  Let me know what you think

**Comment by saranyailla** [comment]
Hi BillMcGuinness, 
Thank you for using our tool. The fix for this bug is already in the development branch of the tool ([commit](https://github.com/aws-greengrass/aws-greengrass-gdk-cli/commit/79630cebbf6452d37154d4113b433fb1b683fdef)) and we used similar workaround like yours :). We will roll this fix out with next version of our tool. 

Closing this issue for now. Please feel free to open it again if you have more concerns. Thanks!
